export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',

  GET_FULL_VACATIONS_LIST_REQUEST: 'GET_FULL_VACATIONS_LIST_REQUEST',
  GET_FULL_VACATIONS_LIST_SUCCESS: 'GET_FULL_VACATIONS_LIST_SUCCESS',
  GET_FULL_VACATIONS_LIST_FAILURE: 'GET_FULL_VACATIONS_LIST_FAILURE',

  GET_EMPLOYEES_LIST_REQUEST: 'GET_EMPLOYEES_LIST_REQUEST',
  GET_EMPLOYEES_LIST_SUCCESS: 'GET_EMPLOYEES_LIST_SUCCESS',
  GET_EMPLOYEES_LIST_FAILURE: 'GET_EMPLOYEES_LIST_FAILURE',

  GET_EMPLOYEE_REQUEST: 'GET_EMPLOYEE_REQUEST',
  GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
  GET_EMPLOYEE_FAILURE: 'GET_EMPLOYEE_FAILURE',

  GET_DEPARTMENT_OPTIONS_REQUEST: 'GET_DEPARTMENT_OPTIONS_REQUEST',
  GET_DEPARTMENT_OPTIONS_SUCCESS: 'GET_DEPARTMENT_OPTIONS_SUCCESS',
  GET_DEPARTMENT_OPTIONS_FAILURE: 'GET_DEPARTMENT_OPTIONS_FAILURE',

  GET_POSITION_OPTIONS_REQUEST: 'GET_POSITION_OPTIONS_REQUEST',
  GET_POSITION_OPTIONS_SUCCESS: 'GET_POSITION_OPTIONS_SUCCESS',
  GET_POSITION_OPTIONS_FAILURE: 'GET_POSITION_OPTIONS_FAILURE',

  SELECT_DEPARTMENT: 'SELECT_DEPARTMENT',
  SELECT_POSITION: 'SELECT_POSITION',
  CHANGE_EMPLOYEES_SEARCH_STRING: 'CHANGE_EMPLOYEES_SEARCH_STRING',
  RESET_EMPLOYEES_FILTERS: 'RESET_EMPLOYEES_FILTERS',
};
