export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  GET_FULL_VACATIONS_LIST_REQUEST: 'GET_FULL_VACATIONS_LIST_REQUEST',
  GET_FULL_VACATIONS_LIST_SUCCESS: 'GET_FULL_VACATIONS_LIST_SUCCESS',
  GET_FULL_VACATIONS_LIST_FAILURE: 'GET_FULL_VACATIONS_LIST_FAILURE',
};
